### PR TITLE
added Azure API support

### PR DESCRIPTION
**Pull request by anubhav06**
Signed-off-by: Anubhav Gupta <mail.anubhav06@gmail.com>

**Added support for Azure's API**
Supported format: `https://<>@dev.azure.com/<>/<>/_git/<>`
Example: `https://anubhav06@dev.azure.com/anubhav06/testing/_git/testing`

For private repo scanning, we need to add the Personal Access Token in the `AZURE_TOKEN` env

The following example shows the working of this Azure API support:

### CODE REVIEW

**Comment by matthyx** [comment]
Hi @anubhav06 great work. I will need a bit of time to review your PR... have you used system tests to validate your Azure API implementation?
Unlike GitHub they don't provide a mock, so it's difficult to ensure they don't change the contracts...

**Comment by anubhav06** [comment]
Hi @matthyx . I haven't added any tests so far. Can we just add tests based on the response we get from the actual API ? (As you said that Azure doesn't provide with mock APIs).

**Comment by matthyx** [comment]
Yup could do with that, at least it will prevent regression on our side. Cheers!

**Comment by anubhav06** [comment]
Okay. I'll add that 👍🏻

**Comment by anubhav06** [comment]
Sorry for the delay, I got caught up with my university work.
Pls let me know if anything else is needed :)

**Comment by matthyx** [comment]
> Sorry for the delay, I got caught up with my university work. Pls let me know if anything else is needed :)

reading through it... wow that's exactly what I had in mind!
let me have a proper look at it tomorrow and merge if OK.
thanks a lot @anubhav06 !

**Comment by matthyx** [comment]
thanks @anubhav06 !

**Pull request merged**
